project:
  name: cic-primitives
  description: CIC meta-schema layer — atomic and aggregate primitives
  license: CC-BY-NC-SA-4.0
  main_branch: primitives/main
  owner: Gabor Zoltan Sinko
  maintenance:
    status: active
    supported_until: '2027-12-31'
  contacts:
    - type: email
      value: sinkog@centralinfracore.hu
  links:
    - name: repository
      url: https://github.com/CentralInfraCore/cic-primitives.git
compiler_settings:
  meta_schemas_dir: ./
  source_dir: schemas
  meta_schema_file: md.meta.schema.yaml
  primitive_schema_file: schemas/index.yaml
  vault_key_name: cic-my-sign-key
x-cic:
  repo_type: primitive
release:
  version: 0.1.2
  timestamp: '2026-05-04T12:43:51.537399+00:00'
  repository_tree_hash: ICIjhrN+UjF+tiTxgIxgzZ9Tpd2DQYrCnRXhXWYEe5g=
  build_hash: qSEb6nHZ2/ghL0gfeg26q5Ln0obNCxh3QHLiH6+xybQ=
  sign: vault:v1:MEQCIH1llzAAh9oZ0JDiuZxS2IyIejtKgnM+kCvSkHUp6nwKAiBPS6E4IazLadvEz7kMsXsJj/vcNJX3IyGD3/3cBwVZQQ==
  cert: '-----BEGIN CERTIFICATE-----

    MIICBjCCAaygAwIBAgIUSnRMR6RPnEbg296XWPOqq/u5PCwwCgYIKoZIzj0EAwIw

    QzELMAkGA1UEBhMCSFUxGTAXBgNVBAoMEENlbnRyYWxJbmZyYUNvcmUxGTAXBgNV

    BAMMEENJQyBEZXZlbG9wZXIgQ0EwHhcNMjYwMzIwMTMyMjU5WhcNMjYxMjMxMTMy

    MjU5WjBFMQswCQYDVQQGEwJIVTEZMBcGA1UECgwQQ2VudHJhbEluZnJhQ29yZTEb

    MBkGA1UEAwwSR2Fib3IgWm9sdGFuIFNpbmtvMFkwEwYHKoZIzj0CAQYIKoZIzj0D

    AQcDQgAEIG2CVmTfmLB9pLLclj7YmP2eedAjklpy4LGrU2ijoiy6Xqpuybv7OgJe

    i+ez31s65NEV8+X/ByeX1cstR988z6N8MHowCQYDVR0TBAIwADAdBgNVHQ4EFgQU

    yZN6AIX/TNnIJ9GwAa/NRN3ujHAwHwYDVR0jBBgwFoAUXn6CHYzPUqU4JVP8g+OS

    WeDYjhcwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF

    BQcDBDAKBggqhkjOPQQDAgNIADBFAiEA+bFzXRoJ4PCQbhAAtpkcMjt0vNj5rEW0

    lOMBGDNyaWkCIB1vmM7PcZzv/c9bIrxF5kqv6QXomouhByUfeNUTbpKW

    -----END CERTIFICATE-----'
